#46 - more dates link
epimorphics/standard-reports-ui pull request #63
Opened 2021-09-29 13:42 UTC by mairead

The issue here was Object.assign called within the JS-routes file passed into the Rails sprockets asset pipeline. IE11 doesn't support Object.assign so the entire JS execution was halted as soon as it throws a console error on Object.assign. 

I added a polyfill to the Sprockets manifest so it would be called above the js-routes to prevent the error from appearing.

2021-09-29 13:54 UTC, joescottdave requested changes
Looks good. Rubocop is failing though.  

@ijdickinson have hit problems with this Gem before, I think we had to pin it at a lower version to avoid problems.

2021-09-29 13:54 UTC, joescottdave commented on public/assets/.sprockets-manifest-4c733f3db87a36dc7d1a215f6e4ea451.json
> +{"files":{"hm_lr_logo-e7d24fa0f7fb8c0dc385e34226605540a3df933a7574b57eeb84671d3f13b673.svg":{"logical_path":"hm_lr_logo.svg","mtime":"2021-09-28T15:40:31+01:00","size":17791,"digest":"e7d24fa0f7fb8c0
What is this file?

2021-09-29 13:55 UTC, mairead commented on public/assets/.sprockets-manifest-4c733f3db87a36dc7d1a215f6e4ea451.json
> +{"files":{"hm_lr_logo-e7d24fa0f7fb8c0dc385e34226605540a3df933a7574b57eeb84671d3f13b673.svg":{"logical_path":"hm_lr_logo.svg","mtime":"2021-09-28T15:40:31+01:00","size":17791,"digest":"e7d24fa0f7fb8c0
I think this is autogenerated by sprockets as a manifest of all the things it bundles with rake

2021-09-29 13:55 UTC, mairead commented
> Looks good. Rubocop is failing though.
> 
> @ijdickinson have hit problems with this Gem before, I think we had to pin it at a lower version to avoid problems.

rubocop definitely has some strong opinions about your choice of language

2021-09-29 14:01 UTC, joescottdave commented
> > Looks good. Rubocop is failing though.
> 
> > 
> 
> > @ijdickinson have hit problems with this Gem before, I think we had to pin it at a lower version to avoid problems.
> 
> 
> 
> rubocop definitely has some strong opinions about your choice of language

Rubyists love the rule of law

2021-09-30 08:37 UTC, ijdickinson approved these changes
Lgtm

2021-09-30 08:56 UTC, merged